package org.eventt.features.tools.splitter

import org.eventt.core.esi.EsiClient
import org.eventt.core.esi.EsiClient.FittingItemDto
import org.eventt.core.esi.EsiClient.FittingRequestDto

data class FittingPushResult(
    val split: Split,
    val success: Boolean,
    val fittingId: Int? = null,
    val error: String? = null,
)

/** Builds ESI fitting payloads from computed splits and pushes them so they show up in-game. */
object FittingPushService {
    fun buildRequest(
        split: Split,
        shipTypeId: Int,
    ): FittingRequestDto {
        val items =
            split.items.map { FittingItemDto(it.typeId, it.quantity, "Cargo") } +
                ShipFittingCatalog.extraFittingItemsFor(shipTypeId).map { FittingItemDto(it.typeId, it.quantity, it.flag) }
        return FittingRequestDto(
            name = "Split ${split.index} - ${formatIskShort(split.totalValue)} ISK",
            description = "Generated by eventt Cargo Splitter",
            shipTypeId = shipTypeId,
            items = items,
        )
    }

    /**
     * Pushes every split sequentially. Continues past a failed split rather than aborting — some
     * fittings created is more useful than none, and the caller can surface per-split pass/fail so
     * the user can retry just what failed.
     */
    fun pushAll(
        characterId: Int,
        splits: List<Split>,
        shipTypeId: Int,
        onProgress: (completed: Int, total: Int) -> Unit = { _, _ -> },
    ): List<FittingPushResult> {
        val results = mutableListOf<FittingPushResult>()
        splits.forEachIndexed { i, split ->
            val req = buildRequest(split, shipTypeId)
            results +=
                try {
                    val fittingId = EsiClient.postCharacterFitting(characterId, req)
                    FittingPushResult(split, true, fittingId)
                } catch (e: Exception) {
                    FittingPushResult(split, false, error = e.message)
                }
            onProgress(i + 1, splits.size)
        }
        return results
    }

    private fun formatIskShort(v: Double): String =
        when {
            v >= 1_000_000_000 -> "%.2fB".format(v / 1_000_000_000)
            v >= 1_000_000 -> "%.2fM".format(v / 1_000_000)
            else -> "%,.0f".format(v)
        }
}
